language: cpp

env:
  matrix:
    - BASE=R3.14.12.6 BUSY=1-6-1 SEQ=2.2.5 ASYN=4-31 CALC=R3-6-1 MOTOR=6-9
    - BASE=R3.15.5 BUSY=1-6-1 SEQ=2.2.5 ASYN=4-31 CALC=R3-6-1 MOTOR=6-9
    # - BASE=R3.16.1 BUSY=1-6-1 SEQ=2.2.5 ASYN=4-31 CALC=4aab3c4 MOTOR=6-9

dist: trusty
addons:
  apt:
    packages:
      - libreadline6-dev  # epics build deps
      - libncurses5-dev
      - perl
      - re2c
      - tmux
      - strace

cache:
  directories:
    - $HOME/.cache/epics
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

script:
  - export CI_SCRIPTS="${TRAVIS_BUILD_DIR}/ci-scripts"
  - source "${CI_SCRIPTS}/epics-config.sh"
  - bash "${CI_SCRIPTS}/install-epics-base.sh"
  # - bash "${CI_SCRIPTS}/install-epics-modules.sh"
  # - bash "${CI_SCRIPTS}/install-epics-iocs.sh"
  # - bash "${CI_SCRIPTS}/run-epics-iocs.sh"
  # - pip install pyepics numpy
  # - bash ${CI_SCRIPTS}/run-pyepics-simulator.sh
  - export VERSION_TAG=${BASE}_busy${BUSY}_seq${SEQ}_asyn${ASYN}_calc${CALC}_motor${MOTOR}
  - export FILE_TO_UPLOAD="${TRAVIS_BUILD_DIR}/epics-ci-${VERSION_TAG}.tar.bz2"
  - tar cvfj ${FILE_TO_UPLOAD} ${EPICS_ROOT} 

deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    file_glob: true
    file: "${FILE_TO_UPLOAD}"
    on:
      tags: true
